### ISSUE TITLE
Управление домофоном

### ISSUE THREAD

**Issue by PascalSI** [instalator/domofon_mqtt#1]
Здравствуйте, я несовсем понял как работает данная схема...
Она позволяет только открать дверь или ответить на звонок, услышать кто это и лишь потом открыть? Можете объяснить поподробнее, пару раз перечитывал тему но все равно не доходит...

**Comment by instalator** [comment]
https://blog.instalator.ru/archives/971

**Comment by PascalSI** [comment]
Именно оттуда я и попал на github....

**Comment by instalator** [comment]
Там все расписано. Аудио интерфейс не делал. Это надо в сторону SIP смотреть

**Comment by PascalSI** [comment]
ок, понял. спс
